In [1]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /opt/conda/lib/python3.9/site-packages (3.0.10)
Requirement already satisfied: et-xmlfile in /opt/conda/lib/python3.9/site-packages (from openpyxl) (1.1.0)

In [ ]:
import pandas as pd
import numpy as np
import os
import openpyxl

# print(os.getcwd())
os.chdir('./snp')
# print(os.getcwd())


# read very large excel file 
wb = openpyxl.load_workbook('data-tham1.xlsx', read_only=True)
# print(wb)
rows = wb.active.rows
first_row = [cell.value for cell in next(rows)]

dt = []
for row in rows:
    record = {}
    for key, cell in zip(first_row, row):
        record[key] = cell.value
    dt.append(record)

# data = pd.read_excel('data-tham.xlsx', index_cols=0, sheet_name='Sheet1', engine="openpyxl")
data = pd.DataFrame(dt)
data.head()

FileNotFoundError: [Errno 2] No such file or directory: './snp'

In [3]:
# data.drop(['contact_text', 'ISP', 'dau so', 'file'], axis=1)
# del data['contact_text']
# del data['ISP']
# del data['dau so']
# del data['file']
# del data['NaN']

data.head()

,NaN,To Name,To Contact,To Address,ISP,Address
0,None,1 Nguyen My Linh 150000,0909238244,1416/35 Lê đức thọ f13 Q gò vấp tp hcm,Mobifone,['hcm']
1,None,8 Thu Hằng 150000,0906198540,đc Hoàng Thu Hằng số nhà 19 Đường Vũ Văn Mật T...,Mobifone,"['bình tỉnh', 'yên bái']"
2,None,5 My Nguyen 150000,0987334331,"Số 6, đường số 9, thôn Agrồng, xã Atiêng, Tây ...",Viettel,['Quảng Nam']
3,None,6 Dau Nôi 150000,0965272850,A6/32u/ tổ 7 ấp1a xã vĩnh lộc a huyện Bình Chá...,Viettel,['hcm']
4,None,2 Nguyễn Khâm 150000,0388581760,Tổ 6 p chánh Lộ Tp Quảng ngãi hẻm 968/40/1 qua...,Viettel,"['Quảng ngãi', 'quang tru']"

In [4]:
# data.to_excel('data-tham1.xlsx')

isp_maps = {
    70: 'Mobifone',
 79: 'Mobifone',
 77: 'Mobifone',
 76: 'Mobifone',
 78: 'Mobifone',
 32: 'Viettel',
 33: 'Viettel',
 34: 'Viettel',
 35: 'Viettel',
 36: 'Viettel',
 37: 'Viettel',
 38: 'Viettel',
 39: 'Viettel',
 83: 'Vinaphone',
 84: 'Vinaphone',
 85: 'Vinaphone',
 81: 'Vinaphone',
 82: 'Vinaphone',
 97: 'Viettel',
 90: 'Mobifone',
 93: 'Mobifone',
 96: 'Viettel',
 98: 'Viettel',
 91: 'Vinaphone',
 92: 'Vietnammobile',
 94: 'Vinaphone',
 89: 'Mobifone',
 88: 'Vinaphone',
 86: 'Viettel',
 55: 'Vietnammobile',
 56: 'Vietnammobile',
 58: 'Vietnammobile',
 87: 'I-telecom',
 52: 'Vietnammobile'
}

In [6]:
data.head()

,NaN,To Name,To Contact,To Address,ISP,Address
0,None,1 Nguyen My Linh 150000,0909238244,1416/35 Lê đức thọ f13 Q gò vấp tp hcm,Mobifone,Ho Chi Minh
1,None,8 Thu Hằng 150000,0906198540,đc Hoàng Thu Hằng số nhà 19 Đường Vũ Văn Mật T...,Mobifone,Other province
2,None,5 My Nguyen 150000,0987334331,"Số 6, đường số 9, thôn Agrồng, xã Atiêng, Tây ...",Viettel,Other province
3,None,6 Dau Nôi 150000,0965272850,A6/32u/ tổ 7 ấp1a xã vĩnh lộc a huyện Bình Chá...,Viettel,Ho Chi Minh
4,None,2 Nguyễn Khâm 150000,0388581760,Tổ 6 p chánh Lộ Tp Quảng ngãi hẻm 968/40/1 qua...,Viettel,Other province

In [5]:
def validate_phone(s: str) -> str:
    if '84' in s:
        return s.replace('84', '0')
    return s


data['To Contact'] = data['To Contact'].astype(str).apply(lambda x: validate_phone(x))
data.head()

,NaN,To Name,To Contact,To Address,ISP,Address
0,None,1 Nguyen My Linh 150000,0909238244,1416/35 Lê đức thọ f13 Q gò vấp tp hcm,Mobifone,['hcm']
1,None,8 Thu Hằng 150000,0906198540,đc Hoàng Thu Hằng số nhà 19 Đường Vũ Văn Mật T...,Mobifone,"['bình tỉnh', 'yên bái']"
2,None,5 My Nguyen 150000,0987334331,"Số 6, đường số 9, thôn Agrồng, xã Atiêng, Tây ...",Viettel,['Quảng Nam']
3,None,6 Dau Nôi 150000,0965272850,A6/32u/ tổ 7 ấp1a xã vĩnh lộc a huyện Bình Chá...,Viettel,['hcm']
4,None,2 Nguyễn Khâm 150000,0388581760,Tổ 6 p chánh Lộ Tp Quảng ngãi hẻm 968/40/1 qua...,Viettel,"['Quảng ngãi', 'quang tru']"

In [6]:
def get_isp_name(maps, key):
     try:
        return maps.get(int(key[1:3]), np.nan)
     except ValueError:
        return np.nan
    
data['ISP'] = data['To Contact'].astype(str).apply(lambda x: get_isp_name(isp_maps, x))

data.head()

,NaN,To Name,To Contact,To Address,ISP,Address
0,None,1 Nguyen My Linh 150000,0909238244,1416/35 Lê đức thọ f13 Q gò vấp tp hcm,Mobifone,['hcm']
1,None,8 Thu Hằng 150000,0906198540,đc Hoàng Thu Hằng số nhà 19 Đường Vũ Văn Mật T...,Mobifone,"['bình tỉnh', 'yên bái']"
2,None,5 My Nguyen 150000,0987334331,"Số 6, đường số 9, thôn Agrồng, xã Atiêng, Tây ...",Viettel,['Quảng Nam']
3,None,6 Dau Nôi 150000,0965272850,A6/32u/ tổ 7 ấp1a xã vĩnh lộc a huyện Bình Chá...,Viettel,['hcm']
4,None,2 Nguyễn Khâm 150000,0388581760,Tổ 6 p chánh Lộ Tp Quảng ngãi hẻm 968/40/1 qua...,Viettel,"['Quảng ngãi', 'quang tru']"

In [7]:
!pip install vietnam-provinces

Collecting vietnam-provinces
  Downloading vietnam_provinces-0.4.3-py3-none-any.whl (718 kB)
     |████████████████████████████████| 718 kB 1.8 MB/s
Collecting fast-enum<2.0.0,>=1.3.0
  Downloading fast_enum-1.3.0-py3-none-any.whl (10 kB)
Collecting Unidecode<2.0.0,>=1.1.2
  Downloading Unidecode-1.3.4-py3-none-any.whl (235 kB)
     |████████████████████████████████| 235 kB 6.5 MB/s
Collecting single-version<2.0.0,>=1.5.1
  Downloading single_version-1.5.1-py3-none-any.whl (4.2 kB)
Collecting logbook<2.0.0,>=1.5.3
  Downloading Logbook-1.5.3.tar.gz (85 kB)
     |████████████████████████████████| 85 kB 3.5 MB/s
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: logbook
  Building wheel for logbook (setup.py) ... done
  Created wheel for logbook: filename=Logbook-1.5.3-cp39-cp39-linux_x86_64.whl size=66393 sha256=b7100ff2119b2404d652253a8d2eb2582852ca5a27dff39e303a0949814b9976
  Stored in directory: /home/phuoc/.cache/pip/wheels/b2/87/64/bc96601e8797f86d972db77d78c18e2d102991bcc027657c4a
Successfully built logbook
Installing collected packages: Unidecode, single-version, logbook, fast-enum, vietnam-provinces
Successfully installed Unidecode-1.3.4 fast-enum-1.3.0 logbook-1.5.3 single-version-1.5.1 vietnam-provinces-0.4.3

In [8]:
import re
import vietnam_provinces
from vietnam_provinces.enums import ProvinceEnum




def location(address: str) -> str:
    provinces = '''
        Hà Nội  Hà Giang  Cao Bằng  Bắc Kạn  Tuyên Quang 
        Lào Cai  Điện Biên  Lai Châu  Sơn La  Yên Bái  
        Hoà Bình  Thái Nguyên  Lạng Sơn  Quảng Ninh  Bắc Giang  
        Phú Thọ  Vĩnh Phúc  Bắc Ninh  Hải Dương  Hải Phòng  
        Hưng Yên  Thái Bình  Hà Nam  Nam Định  Ninh Bình  T
        hanh Hóa  Nghệ An  Hà Tĩnh  Quảng Bình  Quảng Trị  
        Thừa Thiên Huế  Đà Nẵng  Quảng Nam  Quảng Ngãi  Bình Định  
        Phú Yên  Khánh Hòa  Ninh Thuận  Bình Thuận  Kon Tum  Gia Lai  
        Đắk Lắk  Đắk Nông  Lâm Đồng  Bình Phước  Tây Ninh  Bình Dương  
        Đồng Nai  Bà Rịa Vũng Tàu  Hồ Chí Minh  Long An  Tiền Giang  
        Bến Tre  Trà Vinh  Vĩnh Long  Đồng Tháp  An Giang  Kiên Giang  
        Cần Thơ  Hậu Giang  Sóc Trăng  Bạc Liêu  Cà Mau'''
    
    
    pattern = r'''(h.?\sch.?\sm.?nh|h.?\sn.?i|h.?\sgiang|c.?o\sb.?ng|
    b.?c\sk.?n|tuy.?n\squang|l.?o\scai|.?i.?n\sbi.?n|lai\sch.?u|s.?n\sla|
    y.?n\sb.?i|h.?.?\sb.?nh|th.?i\snguy.?n|l.?ng\ss.?n|qu.?ng\sninh|b.?c\sgiang|
    ph.?\sth.?|v.?nh\sph.?c|b.?c\sninh|h.?i\sd.?.?ng|h.?i\sph.?ng|h.?ng\sy.?n|
    th.?i\sb.?nh|h.?\snam|nam\s.?.?nh|ninh\sb.?nh|thanh\sh.?.?|ngh.?\san|h.?\st.?nh|
    qu.?ng\sb.?nh|qu.?ng\str.?|th.?a\sthi.?n\shu.?|.?.?\sn.?ng|qu.?ng\snam|qu.?ng\sng.?i|
    b.?nh\s.?.?nh|ph.?\sy.?n|kh.?nh\sh.?a|ninh\sthu.?n|b.?nh\sthu.?n|kon\stum|
    gia\slai|.?.?k\sl.?k|.?.?k\sn.?ng|l.?m\s.?.?ng|b.?nh\sph.?.?c|t.?y\sninh|
    b.?nh\sd.?.?ng|.?.?ng\snai|b.?\sr.?a\s-\sv.?ng\st.?u|long\san|ti.?n\sgiang|
    b.?n\stre|tr.?\svinh|v.?nh\slong|.?.?ng\sth.?p|an\sgiang|ki.?n\sgiang|c.?n\sth.?|
    h.?u\sgiang|s.?c\str.?ng|b.?c\sli.?u|c.?\smau|hn|hcm)'''
    
    try:
        array_of_result =  re.findall(pattern, address, re.IGNORECASE)
        return array_of_result
    except TypeError:
        return "sai dia chi"


    
location('1')


# data['Address'] = data['To Address'].apply(lambda x: location(x))

# data.head()

,NaN,To Name,To Contact,To Address,ISP,Address
0,None,1 Nguyen My Linh 150000,0909238244,1416/35 Lê đức thọ f13 Q gò vấp tp hcm,Mobifone,[hcm]
1,None,8 Thu Hằng 150000,0906198540,đc Hoàng Thu Hằng số nhà 19 Đường Vũ Văn Mật T...,Mobifone,"[bình tỉnh, yên bái]"
2,None,5 My Nguyen 150000,0987334331,"Số 6, đường số 9, thôn Agrồng, xã Atiêng, Tây ...",Viettel,[Quảng Nam]
3,None,6 Dau Nôi 150000,0965272850,A6/32u/ tổ 7 ấp1a xã vĩnh lộc a huyện Bình Chá...,Viettel,[hcm]
4,None,2 Nguyễn Khâm 150000,0388581760,Tổ 6 p chánh Lộ Tp Quảng ngãi hẻm 968/40/1 qua...,Viettel,"[Quảng ngãi, quang tru]"

In [79]:
data.head()

,NaN,To Name,To Contact,To Address,ISP,Address
0,None,1 Nguyen My Linh 150000,0909238244,1416/35 Lê đức thọ f13 Q gò vấp tp hcm,Mobifone,[hcm]
1,None,8 Thu Hằng 150000,0906198540,đc Hoàng Thu Hằng số nhà 19 Đường Vũ Văn Mật T...,Mobifone,"[bình tỉnh, yên bái]"
2,None,5 My Nguyen 150000,0987334331,"Số 6, đường số 9, thôn Agrồng, xã Atiêng, Tây ...",Viettel,[Quảng Nam]
3,None,6 Dau Nôi 150000,0965272850,A6/32u/ tổ 7 ấp1a xã vĩnh lộc a huyện Bình Chá...,Viettel,[hcm]
4,None,2 Nguyễn Khâm 150000,0388581760,Tổ 6 p chánh Lộ Tp Quảng ngãi hẻm 968/40/1 qua...,Viettel,"[Quảng ngãi, quang tru]"

In [23]:
# data.to_excel('data-tham1.xlsx')

def split_df(df, chunksize=10000):
    chunks = []
    num_chunks = len(df) // chunksize + 1
    for i in range(num_chunks):
        chunks.append(df[i*chunksize:(i+1)*chunksize])
    return chunks

# chunksize = 10000
# chunks = len(data) // chunksize
chunks = split_df(data)

i = 0
for chunk in chunks:
    chunk.to_excel('data-tham_{:02d}.xlsx'.format(i), index=False)
    i += 1

In [59]:
from vietnam_provinces.enums import ProvinceEnum

d = [e.value.name for e in ProvinceEnum]
s = ' '.join(d).replace('Thành phố', '').replace('Tỉnh', '').strip()
s

'Hà Nội  Hà Giang  Cao Bằng  Bắc Kạn  Tuyên Quang  Lào Cai  Điện Biên  Lai Châu  Sơn La  Yên Bái  Hoà Bình  Thái Nguyên  Lạng Sơn  Quảng Ninh  Bắc Giang  Phú Thọ  Vĩnh Phúc  Bắc Ninh  Hải Dương  Hải Phòng  Hưng Yên  Thái Bình  Hà Nam  Nam Định  Ninh Bình  Thanh Hóa  Nghệ An  Hà Tĩnh  Quảng Bình  Quảng Trị  Thừa Thiên Huế  Đà Nẵng  Quảng Nam  Quảng Ngãi  Bình Định  Phú Yên  Khánh Hòa  Ninh Thuận  Bình Thuận  Kon Tum  Gia Lai  Đắk Lắk  Đắk Nông  Lâm Đồng  Bình Phước  Tây Ninh  Bình Dương  Đồng Nai  Bà Rịa - Vũng Tàu  Hồ Chí Minh  Long An  Tiền Giang  Bến Tre  Trà Vinh  Vĩnh Long  Đồng Tháp  An Giang  Kiên Giang  Cần Thơ  Hậu Giang  Sóc Trăng  Bạc Liêu  Cà Mau'

In [1]:
def location1(address: str) -> str:
    provinces = '''
        Hà Nội  Hà Giang  Cao Bằng  Bắc Kạn  Tuyên Quang 
        Lào Cai  Điện Biên  Lai Châu  Sơn La  Yên Bái  
        Hoà Bình  Thái Nguyên  Lạng Sơn  Quảng Ninh  Bắc Giang  
        Phú Thọ  Vĩnh Phúc  Bắc Ninh  Hải Dương  Hải Phòng  
        Hưng Yên  Thái Bình  Hà Nam  Nam Định  Ninh Bình  T
        hanh Hóa  Nghệ An  Hà Tĩnh  Quảng Bình  Quảng Trị  
        Thừa Thiên Huế  Đà Nẵng  Quảng Nam  Quảng Ngãi  Bình Định  
        Phú Yên  Khánh Hòa  Ninh Thuận  Bình Thuận  Kon Tum  Gia Lai  
        Đắk Lắk  Đắk Nông  Lâm Đồng  Bình Phước  Tây Ninh  Bình Dương  
        Đồng Nai  Bà Rịa - Vũng Tàu  Hồ Chí Minh  Long An  Tiền Giang  
        Bến Tre  Trà Vinh  Vĩnh Long  Đồng Tháp  An Giang  Kiên Giang  
        Cần Thơ  Hậu Giang  Sóc Trăng  Bạc Liêu  Cà Mau'''
    
    
    pattern = r'(h.?\sch.?\sm.?nh|h.?\sn.?i|h.?\sgiang|c.?o\sb.?ng|b.?c\sk.?n|tuy.?n\squang|l.?o\scai|.?i.?n\sbi.?n|lai\sch.?u|s.?n\sla|y.?n\sb.?i|h.?a\sb.?nh|th.?i\snguy.?n|l.?ng\ss.?n|qu.?ng\sninh|b.?c\sgiang|ph.?\sth.?|v.?nh\sph.?c|b.?c\sninh|h.?i\sd.?.?ng|h.?i\sph.?ng|h.?ng\sy.?n|th.?i\sb.?nh|h.?\snam|nam\s.?.?nh|ninh\sb.?nh|thanh\sh.?a|ngh.?\san|h.?\st.?nh|qu.?ng\sb.?nh|qu.?ng\str.?|th.?a\sthi.?n\shu.?|.?.?\sn.?ng|qu.?ng\snam|qu.?ng\sng.?i|b.?nh\s.?.?nh|ph.?\sy.?n|kh.?nh\sh.?a|ninh\sthu.?n|b.?nh\sthu.?n|kon\stum|gia\slai|.?.?k\sl.?k|.?.?k\sn.?ng|l.?m\s.?.?ng|b.?nh\sph.?.?c|t.?y\sninh|b.?nh\sd.?.?ng|.?.?ng\snai|b.?\sr.?a\s-\sv.?ng\st.?u|long\san|ti.?n\sgiang|b.?n\stre|tr.?\svinh|v.?nh\slong|.?.?ng\sth.?p|an\sgiang|ki.?n\sgiang|c.?n\sth.?|h.?u\sgiang|s.?c\str.?ng|b.?c\sli.?u|c.?\smau|hn|hcm)'
    
    def check(l: list) -> str:
        for e in l:
            if e in provinces:
                return e
        
        return "sai dia chi"
    
    
    try:
        array_of_result =  re.findall(pattern, address, re.IGNORECASE)
        return array_of_result
    except TypeError:
        return "sai dia chi"

    
print(location1('123 le quang dinh, ho chi minh'))

NameError: name 're' is not defined